const departementsData = [
  {
    number: 1,
    alias: "",
    name: "l'Ain",
    capital: "Bourg-en-Bresse",
    adminRegion: "Auvergne-Rhône-Alpes",
    codePostal: "01000"
  },
  {
    number: 2,
    alias: "",
    name: "l'Aisne",
    capital: "Laon",
    adminRegion: "Hauts-de-France",
    codePostal: "02000"
  },
  {
    number: 3,
    alias: "",
    name: "l'Allier",
    capital: "Moulins",
    adminRegion: "Auvergne-Rhône-Alpes",
    codePostal: "03000"
  },
  {
    number: 4,
    alias: "",
    name: "les Alpes de Haute-Provence",
    capital: "Digne-les-Bains",
    adminRegion: "Provence-Alpes-Côte d'Azur",
    codePostal: "04000"
  },
  {
    number: 5,
    alias: "",
    name: "les Haute-Alpes",
    capital: "Gap",
    adminRegion: "Provence-Alpes-Côte d'Azur",
    codePostal: "05000"
  },
  {
    number: 6,
    alias: "",
    name: "les Alpes-Maritimes",
    capital: "Nice",
    adminRegion: "Provence-Alpes-Côte d'Azur",
    codePostal: "06000"
  },
  {
    number: 7,
    alias: "",
    name: "l'Ardèche",
    capital: "Privas",
    adminRegion: "Auvergne-Rhône-Alpes",
    codePostal: "07000"
  },
  {
    number: 8,
    alias: "",
    name: "les Ardennes",
    capital: "Charleville-Mézières",
    adminRegion: "Grand Est",
    codePostal: "08000"
  },
  {
    number: 9,
    alias: "",
    name: "l'Ariège",
    capital: "Foix",
    adminRegion: "Occitanie",
    codePostal: "09000"
  },
  {
    number: 10,
    alias: "",
    name: "l'Aube",
    capital: "Troyes",
    adminRegion: "Grand Est",
    codePostal: "10000"
  },
  {
    number: 11,
    alias: "",
    name: "l'Aude",
    capital: "Carcassonne",
    adminRegion: "Occitanie",
    codePostal: "11000"
  },
  {
    number: 12,
    alias: "",
    name: "l'Aveyron",
    capital: "Rodez",
    adminRegion: "Occitanie",
    codePostal: "12000"
  },
  {
    number: 13,
    alias: "",
    name: "les Bouches-du-Rhônes",
    capital: "Marseille",
    adminRegion: "Provence-Alpes-Côte d'Azur",
    codePostal: "13000"
  },
  {
    number: 14,
    alias: "",
    name: "le Calvados",
    capital: "Caen",
    adminRegion: "Normandie",
    codePostal: "14000"
  },
  {
    number: 15,
    alias: "",
    name: "le Cantal",
    capital: "Aurillac",
    adminRegion: "Auvergne-Rhône-Alpes",
    codePostal: "15000"
  },
  {
    number: 16,
    alias: "",
    name: "la Charente",
    capital: "Angoulème",
    adminRegion: "Nouvelle-Aquitaine",
    codePostal: "16000"
  },
  {
    number: 17,
    alias: "",
    name: "la Charente-Maritime",
    capital: "La Rochelle",
    adminRegion: "Nouvelle-Aquitaine",
    codePostal: "17000"
  },
  {
    number: 18,
    alias: "",
    name: "le Cher",
    capital: "Bourges",
    adminRegion: "Centre Val de Loire",
    codePostal: "18000"
  },
  {
    number: 19,
    alias: "",
    name: "la Corrèze",
    capital: "Tulle",
    adminRegion: "Nouvelle-Aquitaine",
    codePostal: "19000"
  },
  {
    number: 20.1,
    alias: "A",
    name: "la Corse-du-Sud",
    capital: "Ajaccio",
    adminRegion: "Corse",
    codePostal: "20000"
  },
  {
    number: 20.2,
    alias: "B",
    name: "la Haute-Corse",
    capital: "Bastia",
    adminRegion: "Corse",
    codePostal: "20200"
  },
  {
    number: 21,
    alias: "",
    name: "la Côte-d'Or",
    capital: "Dijon",
    adminRegion: "Bourgogne-Franche-Comté",
    codePostal: "21000"
  },
  {
    number: 22,
    alias: "",
    name: "les Côtes d'Armor",
    capital: "Saint-Brieuc",
    adminRegion: "Bretagne",
    codePostal: "22000"
  },
  {
    number: 23,
    alias: "",
    name: "la Creuse",
    capital: "Guéret",
    adminRegion: "Nouvelle-Aquitaine",
    codePostal: "23000"
  },
  {
    number: 24,
    alias: "",
    name: "la Dordogne",
    capital: "Périgueux",
    adminRegion: "Nouvelle-Aquitaine",
    codePostal: "24000"
  },
  {
    number: 25,
    alias: "",
    name: "le Doubs",
    capital: "Besançon",
    adminRegion: "Bourgogne-Franche-Comté",
    codePostal: "25000"
  },
  {
    number: 26,
    alias: "",
    name: "la Drôme",
    capital: "Valence",
    adminRegion: "Auvergne-Rhône-Alpes",
    codePostal: "26000"
  },
  {
    number: 27,
    alias: "",
    name: "l'Eure",
    capital: "Evreux",
    adminRegion: "Normandie",
    codePostal: "27000"
  },
  {
    number: 28,
    alias: "",
    name: "l'Eure-et-Loir",
    capital: "Chartres",
    adminRegion: "Centre Val de Loire",
    codePostal: "28000"
  },
  {
    number: 29,
    alias: "",
    name: "le Finistère",
    capital: "Quimper",
    adminRegion: "Bretagne",
    codePostal: "29000"
  },
  {
    number: 30,
    alias: "",
    name: "le Gard",
    capital: "Nîmes",
    adminRegion: "Occitanie",
    codePostal: "30000"
  },
  {
    number: 31,
    alias: "",
    name: "la Haute-Garonne",
    capital: "Toulouse",
    adminRegion: "Occitanie",
    codePostal: "31000"
  },
  {
    number: 32,
    alias: "",
    name: "le Gers",
    capital: "Auch",
    adminRegion: "Occitanie",
    codePostal: "32000"
  },
  {
    number: 33,
    alias: "",
    name: "la Gironde",
    capital: "Bordeaux",
    adminRegion: "Nouvelle-Aquitaine",
    codePostal: "33000"
  },
  {
    number: 34,
    alias: "",
    name: "l'Hérault",
    capital: "Montpellier",
    adminRegion: "Occitanie",
    codePostal: "34000"
  },
  {
    number: 35,
    alias: "",
    name: "l'Ille-et-Vilaine",
    capital: "Rennes",
    adminRegion: "Bretagne",
    codePostal: "35000"
  },
  {
    number: 36,
    alias: "",
    name: "l'Indre",
    capital: "Châteauroux",
    adminRegion: "Centre Val de Loire",
    codePostal: "36000"
  },
  {
    number: 37,
    alias: "",
    name: "l'Indre-et-Loire",
    capital: "Tours",
    adminRegion: "Centre Val de Loire",
    codePostal: "37000"
  },
  {
    number: 38,
    alias: "",
    name: "l'Isère",
    capital: "Grenoble",
    adminRegion: "Auvergne-Rhône-Alpes",
    codePostal: "38000"
  },
  {
    number: 39,
    alias: "",
    name: "le Jura",
    capital: "Lons-le-Saunier",
    adminRegion: "Bourgogne-Franche-Comté",
    codePostal: "39000"
  },
  {
    number: 40,
    alias: "",
    name: "les Landes",
    capital: "Mont-de-Marsan",
    adminRegion: "Nouvelle-Aquitaine",
    codePostal: "40000"
  },
  {
    number: 41,
    alias: "",
    name: "le Loir-et-Cher",
    capital: "Blois",
    adminRegion: "Centre Val de Loire",
  },
  {
    number: 42,
    alias: "",
    name: "la Loire",
    capital: "Saint-Etienne",
    adminRegion: "Auvergne-Rhône-Alpes",
  },
  {
    number: 43,
    alias: "",
    name: "la Haute-Loire",
    capital: "Le-Puy-en-Velay",
    adminRegion: "Auvergne-Rhône-Alpes",
  },
  {
    number: 44,
    alias: "",
    name: "la Loire-Atlantique",
    capital: "Nantes",
    adminRegion: "Pays de la Loire",
  },
  {
    number: 45,
    alias: "",
    name: "le Loiret",
    capital: "Orléans",
    adminRegion: "Centre Val de Loire",
  },
  {
    number: 46,
    alias: "",
    name: "le Lot",
    capital: "Cahors",
    adminRegion: "Occitanie",
  },
  {
    number: 47,
    alias: "",
    name: "le Lot-et-Garonne",
    capital: "Agen",
    adminRegion: "Nouvelle-Aquitaine",
  },
  {
    number: 48,
    alias: "",
    name: "la Lozère",
    capital: "Mende",
    adminRegion: "Occitanie",
  },
  {
    number: 49,
    alias: "",
    name: "le Maine-et-Loire",
    capital: "Angers",
    adminRegion: "Pays de la Loire",
  },
  {
    number: 50,
    alias: "",
    name: "la Manche",
    capital: "Saint-Lô",
    adminRegion: "Normandie",
  },
  {
    number: 51,
    alias: "",
    name: "la Marne",
    capital: "Châlons-en-Champagne",
    adminRegion: "Grand Est",
  },
  {
    number: 52,
    alias: "",
    name: "la Haute-Marne",
    capital: "Chaumont",
    adminRegion: "Grand Est",
  },
  {
    number: 53,
    alias: "",
    name: "la Mayenne",
    capital: "Laval",
    adminRegion: "Pays de la Loire",
  },
  {
    number: 54,
    alias: "",
    name: "la Meurthe-et-Moselle",
    capital: "Nancy",
    adminRegion: "Grand Est",
  },
  {
    number: 55,
    alias: "",
    name: "la Meuse",
    capital: "Bar-le-Duc",
    adminRegion: "Grand Est",
  },
  {
    number: 56,
    alias: "",
    name: "le Morbihan",
    capital: "Vannes",
    adminRegion: "Bretagne",
  },
  {
    number: 57,
    alias: "",
    name: "la Moselle",
    capital: "Metz",
    adminRegion: "Grand Est",
  },
  {
    number: 58,
    alias: "",
    name: "la Nièvre",
    capital: "Nevers",
    adminRegion: "Bourgogne-Franche-Comté",
  },
  {
    number: 59,
    alias: "",
    name: "le Nord",
    capital: "Lille",
    adminRegion: "Hauts-de-France",
  },
  {
    number: 60,
    alias: "",
    name: "l'Oise",
    capital: "Beauvais",
    adminRegion: "Hauts-de-France",
  },
  {
    number: 61,
    alias: "",
    name: "l'Orne",
    capital: "Alençon",
    adminRegion: "Normandie",
  },
  {
    number: 62,
    alias: "",
    name: "le Pas-de-Calais",
    capital: "Arras",
    adminRegion: "Hauts-de-France",
  },
  {
    number: 63,
    alias: "",
    name: "le Puy-de-Dôme",
    capital: "Clermont-Ferrand",
    adminRegion: "Auvergne-Rhône-Alpes",
  },
  {
    number: 64,
    alias: "",
    name: "les Pyrénées-Atlantiques",
    capital: "Pau",
    adminRegion: "Nouvelle-Aquitaine",
  },
  {
    number: 65,
    alias: "",
    name: "les Hautes-Pyrénées",
    capital: "Tarbes",
    adminRegion: "Occitanie",
  },
  {
    number: 66,
    alias: "",
    name: "les Pyrénées-Orientales",
    capital: "Perpignan",
    adminRegion: "Occitanie",
  },
  {
    number: 67,
    alias: "",
    name: "le Bas-Rhin",
    capital: "Strasbourg",
    adminRegion: "Grand Est",
  },
  {
    number: 68,
    alias: "",
    name: "le Haut-Rhin",
    capital: "Colmar",
    adminRegion: "Grand Est",
  },
  {
    number: 69,
    alias: "",
    name: "le Rhône",
    capital: "Lyon",
    adminRegion: "Auvergne-Rhône-Alpes",
  },
  {
    number: 70,
    alias: "",
    name: "la Haute-Saône",
    capital: "Vesoul",
    adminRegion: "Bourgogne-Franche-Comté",
  },
  {
    number: 71,
    alias: "",
    name: "la Saône-et-Loire",
    capital: "Mâcon",
    adminRegion: "Bourgogne-Franche-Comté",
  },
  {
    number: 72,
    alias: "",
    name: "la Sarthe",
    capital: "Le Mans",
    adminRegion: "Pays de la Loire",
  },
  {
    number: 73,
    alias: "",
    name: "la Savoie",
    capital: "Chambéry",
    adminRegion: "Auvergne-Rhône-Alpes",
  },
  {
    number: 74,
    alias: "",
    name: "la Haute-Savoie",
    capital: "Annecy",
    adminRegion: "Auvergne-Rhône-Alpes",
  },
  {
    number: 75,
    alias: "",
    name: "Paris",
    capital: "Paris",
    adminRegion: "Ile-de-France",
  },
  {
    number: 76,
    alias: "",
    name: "la Seine-Maritime",
    capital: "Rouen",
    adminRegion: "Normandie",
  },
  {
    number: 77,
    alias: "",
    name: "la Seine-et-Marne",
    capital: "Melun",
    adminRegion: "Ile-de-France",
  },
  {
    number: 78,
    alias: "",
    name: "les Yvelines",
    capital: "Versailles",
    adminRegion: "Ile-de-France",
  },
  {
    number: 79,
    alias: "",
    name: "les Deux-Sèvres",
    capital: "Niort",
    adminRegion: "Nouvelle-Aquitaine",
  },
  {
    number: 80,
    alias: "",
    name: "la Somme",
    capital: "Amiens",
    adminRegion: "Hauts-de-France",
  },
  {
    number: 81,
    alias: "",
    name: "le Tarn",
    capital: "Albi",
    adminRegion: "Occitanie",
  },
  {
    number: 82,
    alias: "",
    name: "le Tarn-et-Garonne",
    capital: "Montauban",
    adminRegion: "Occitanie",
  },
  {
    number: 83,
    alias: "",
    name: "le Var",
    capital: "Toulon",
    adminRegion: "Provence-Alpes-Côte d'Azur",
  },
  {
    number: 84,
    alias: "",
    name: "le Vaucluse",
    capital: "Avignon",
    adminRegion: "Provence-Alpes-Côte d'Azur",
  },
  {
    number: 85,
    alias: "",
    name: "la Vendée",
    capital: "La Roche-sur-Yon",
    adminRegion: "Pays de la Loire",
  },
  {
    number: 86,
    alias: "",
    name: "la Vienne",
    capital: "Poitiers",
    adminRegion: "Nouvelle-Aquitaine",
  },
  {
    number: 87,
    alias: "",
    name: "la Haute-Vienne",
    capital: "Limoges",
    adminRegion: "Nouvelle-Aquitaine",
  },
  {
    number: 88,
    alias: "",
    name: "les Vosges",
    capital: "Epinal",
    adminRegion: "Grand Est",
  },
  {
    number: 89,
    alias: "",
    name: "l'Yonne",
    capital: "Auxerre",
    adminRegion: "Bourgogne-Franche-Comté",
  },
  {
    number: 90,
    alias: "",
    name: "le Territoire-de-Belfort",
    capital: "Belfort",
    adminRegion: "Bourgogne-Franche-Comté",
  },
  {
    number: 91,
    alias: "",
    name: "l'Essonne",
    capital: "Evry",
    adminRegion: "Ile-de-France",
  },
  {
    number: 92,
    alias: "",
    name: "les Hauts-de-Seine",
    capital: "Nanterre",
    adminRegion: "Ile-de-France",
  },
  {
    number: 93,
    alias: "",
    name: "la Seine-Saint-Denis",
    capital: "Bobigny",
    adminRegion: "Ile-de-France",
  },
  {
    number: 94,
    alias: "",
    name: "le Val-de-Marne",
    capital: "Créteil",
    adminRegion: "Ile-de-France",
  },
  {
    number: 95,
    alias: "",
    name: "le Val-d'Oise",
    capital: "Pontoise",
    adminRegion: "Ile-de-France",
  },
  {
    number: 971,
    alias: "",
    name: "la Guadeloupe",
    capital: "Basse-Terre",
    adminRegion: "Guadeloupe",
  },
  {
    number: 972,
    alias: "",
    name: "la Martinique",
    capital: "Fort-de-France",
    adminRegion: "Martinique",
  },
  {
    number: 973,
    alias: "",
    name: "la Guyane",
    capital: "Cayenne",
    adminRegion: "Guyane",
  },
  {
    number: 974,
    alias: "",
    name: "La Réunion",
    capital: "Saint-Denis",
    adminRegion: "La Réunion",
  },
  {
    number: 976,
    alias: "",
    name: "Mayotte",
    capital: "Dzaoudzi",
    adminRegion: "Mayotte",
  },
];

export default departementsData;
